package main

import (
	"context"
	swagger "github.com/arsmn/fiber-swagger/v2"
	"go-rest/controller"
	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "go-rest/docs"
	"go-rest/service"
)

var (
	ctx = context.WithValue(context.Background(), "requestId", "main")
)

// @title GO REST API
// @version 2.0
// @description This is a sample server.
// @termsOfService http://swagger.io/terms/

// @host localhost:8080
// @BasePath /
// @schemes http
func main() {
	barService := service.NewBarService()
	fooService := service.NewFooService()

	controllers := controller.ApiControllers{
		FooController:     controller.NewFooController(fooService),
		BarController:     controller.NewBarController(barService),
		GeneralController: controller.NewGeneralController(),
	}

	app := controller.CreateApi(ctx, controllers)
	app.Get("/swagger/*", swagger.HandlerDefault) // default
	//registerShutdownHook(app)

	serverBind := ":8080"
	if err := app.Listen(serverBind); err != nil {
		println(err.Error())
	}

	println("Example server gracefully finished")
}
